# Generated by Django 3.2.4 on 2022-08-28 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('surname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('date_birth', models.DateField()),
                ('created_at', models.DateField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.languages')),
            ],
        ),
    ]
